# Railway configuration for smor-ting backend service

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "./smor-ting-api"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Environment variables for Railway
[env]
PORT = { default = "8080" }
ENV = { default = "production" }
HOST = { default = "0.0.0.0" }
READ_TIMEOUT = { default = "30s" }
WRITE_TIMEOUT = { default = "30s" }
IDLE_TIMEOUT = { default = "120s" }
