# Nixpacks config for monorepo: build the Go backend in smor_ting_backend

[variables]
# Railway provides PORT; do not override. Keep for local builds if needed.
PORT = "8080"

[phases.setup]
nixPkgs = ["go_1_21"]

[phases.install]
commands = [
  "go env -w GOPATH=/root/go",
  "go mod download",
]
workingDirectory = "smor_ting_backend"

[phases.build]
commands = [
  "go build -o server ./cmd",
]
workingDirectory = "smor_ting_backend"

[start]
cmd = "./server"
workingDirectory = "smor_ting_backend"

