# DEPRECATED: nixpacks.toml - Using Dockerfile instead
# This file is kept for reference but Railway will use Dockerfile
# To use this instead, remove the Dockerfile from smor_ting_backend/

[variables]
PORT = "8080"

[phases.setup]
nixPkgs = ["go_1_21"]

[phases.install]
commands = [
  "go env -w GOPATH=/root/go",
  "go mod download",
]
workingDirectory = "smor_ting_backend"

[phases.build]
commands = [
  "go build -o smor-ting-api ./cmd",
]
workingDirectory = "smor_ting_backend"

[start]
cmd = "./smor-ting-api"
workingDirectory = "smor_ting_backend"

