# Railway configuration for smor-ting monorepo
# This tells Railway to build the backend service

[build]
builder = "DOCKERFILE"
dockerfilePath = "smor_ting_backend/Dockerfile"
watchPatterns = [
  "smor_ting_backend/**/*",
  "smor_ting_backend/*",
  "smor_ting_backend/cmd/**/*",
  "smor_ting_backend/configs/**/*",
  "smor_ting_backend/Dockerfile",
  "smor_ting_backend/go.mod",
  "smor_ting_backend/go.sum"
]

[deploy]
startCommand = "./smor-ting-api"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Environment variables for Railway
[env]
PORT = { default = "8080" }
ENV = { default = "production" }
HOST = { default = "0.0.0.0" }
# Updated: $(date +%s) - Fixed watch patterns permanently
# This configuration ensures Railway detects ALL backend file changes
